## Calendar

##### Week 1

- Tuesday, January 21
   - Introduction to the course
   - watch [Powers of 10](#powers)

- Thursday, January 23
   - blog and [Hypothes.is](#appendix) workshop
   - write 2 annotations (remember to choose the SoS\@PSU group)
    
##### Week 2

- Tuesday, January 28
   - read [The origins of science](#origins)

   
- Thursday, January 30
   - read [Magical thinking](#magical-thinking)
   - write 2 annotations (remember to choose the SoS\@PSU group)


##### Week 3

- Tuesday, February 4
   - read [Philosophy, skepticism and critcal thinking](#philosophy)
   - **groups 1, 2, 3: featured posts due**
   

- Thursday, February 6
   - in class activity: [Case study 1](#case-1)
   - write 2 annotations 


##### Week 4

- Tuesday, February 11
   - read [The scientific revolution](#revolution)
   - **groups 4, 5, 6: featured posts due**

- Thursday, February 13
   - read [The problem of knowledge](#knowledge)
   - write 2 annotations 



##### Week 5

- Tuesday, February 18
   - read [Visual illusions](#visual-illusions)
   - **groups 7, 8: featured posts due**

- Thursday, February 20
   - read [Logic: the basics](#logic)
   - write 2 annotations 



##### Week 6

- Tuesday, February 25
   - in class activity: **group project planning**
   - **groups 1, 2, 3: featured posts due**

- Thursday, February 27
   - in class activity: [Case study 2](#case-2)
   - write 2 annotations 



##### Week 7

- Tuesday, March 3
   - read [Matter and Energy](#matter)
   - **groups 4, 5, 6: featured posts due**

- Thursday, March 5
   - Merchants of Doubt
   - write 2 annotations 

##### SPRING BREAK: March 6 -- 15

##### Week 8

- Tuesday, March 17
   - read [Freedom and Determinism](#freedom)
   - **groups 7, 8: featured posts due**

- Thursday, March 19
   - read [Science and Pseudoscience](#pseudoscience)
   - write 2 annotations 

##### Week 9

- Tuesday, March 24
   - in class activity: [Case study 3](#case-3)
   - **groups 1, 2, 3: featured posts due**

- Thursday, March 26
   - read [Evolution](#evolution)
   - write 2 annotations 


##### Week 10

- Tuesday, March 31
   - [Engineering life](#biotechnology)
   - **groups 4, 5, 6: featured posts due**

- Thursday, April 2
   - in class activity: **group project planning**
   - write 2 annotations 


##### Week 11

- Tuesday, April 7
   - [Science denial](#denial)
   - **groups 7, 8: featured posts due**

- Thursday, April 9
   - in class activity: [Case study 4](#case-4)
   - write 2 annotations 

##### Week 12

- Tuesday, April 14
   - [Psychology: studying ourselves](#psychology)

- Thursday, April 16
   - [Minds and machines](#mind-machine)
   - write 2 annotations 


##### Week 13

- Tuesday, April 21
   - [A simple experiment](#stanford)
   - **group project posts due**

- Thursday, April 23
   - [The psychology of conspiracy theories](#conspiracy)
   - write 2 annotations 

##### Week 14

- Tuesday, April 28
   - in class activity: [Case study 5](#case-5)

- Thursday, April 30
   - in class activity: fishbowl discussion
