## Science and pseudoscience

The nineteenth century not only saw the explosive  growth of scientific and technical knowledge about the workings of the material world. It also saw the development of modern spiritualism, phrenology (which claimed to be able to determine the character traits of someone based on the shape of their head), the the "science" of human racial types, hypnotism, parapsychology, modern astrology and other not-quite-scientific attempts to provide a scientific basis for a picture of the world that was directly threatened by the materialism implicit in nineteenth century science. What all of these approaches have in common is the attempt to use quasi-scientific methods to validate beliefs that were directly threatened by developments in science. 

From a philosophical point of view, we are here wandering into the murky waters of the "demarcation problem."

:::{.question data-latex="" .infobox}

How can we distinguish "real" science from pseudo-scientific impostors, those approaches that claim to be scientific but are really something different?

:::

The difficulty of this problem comes from the difficulty of spelling out a series of necessary and sufficient conditions for something being real science, especially since the pretenders to science often argue that their views meet those same criteria. Is this just a matter of turf wars between the establishment and the fringe? Is this really an ideological battle between two different world views one of which claims that all that exists is matter and energy, and the other of which claims that there has to be something *more* -- a soul, a spiritual world, a deeper and hidden meaning to things rather than just atoms in empty space?

This article presents the basic question and discusses Karl Popper's famous solution to the "demarcation problem" which hinges on his idea that the best scientific theories are *not* the ones that have been somehow proven correct or verified, but the ones that *could* be but have not yet been *falsified.* That may seem like a roundabout way of talking but for Popper the crucial difference between legitimate and illegitimate approaches to science is that scientific claims take risks and so tells us something new about reality while pseudosceintific theories do not and hence never get beyond stating what their proponents already think they know.

:::{.embedcard}

<blockquote class="embedly-card"><h4><a href="https://www.scientificamerican.com/article/what-is-pseudoscience/">What Is Pseudoscience?</a></h4><p>Climate deniers are accused of practicing pseudoscience, as are intelligent design creationists, astrologers, UFOlogists, parapsychologists, practitioners of alternative medicine, and often anyone who strays far from the scientific mainstream.</p></blockquote>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>

:::

Here is another take on the topic by Hank Green from the Crash Course video series.


:::{.video}

<iframe width="560" height="315" src="https://www.youtube.com/embed/-X8Xfl0JdTQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

:::
